export { Message } from './message.aggregate.js';
export { MessageStatus, MessageDirection } from './message-status.js';
export { DeliveryAttempt, DeliveryAttemptStatus } from './entities/delivery-attempt.entity.js';
export { PhoneNumber } from './value-objects/phone-number.vo.js';
export { MessageContent, MessageContentType } from './value-objects/message-content.vo.js';
export { RetryPolicy } from './value-objects/retry-policy.vo.js';
export { ProviderMessageRef } from './value-objects/provider-message-ref.vo.js';
export { FailureReason, FailureCategory } from './value-objects/failure-reason.vo.js';
export { InvalidStateTransitionError } from './errors/invalid-state-transition.error.js';
export type { IMessageState } from './states/message-state.interface.js';
export type { IMessageRepository } from './ports/message-repository.port.js';
export { MessageCreatedEvent } from './events/message-created.event.js';
export { MessageQueuedEvent } from './events/message-queued.event.js';
export { MessageSendingEvent } from './events/message-sending.event.js';
export { MessageSentEvent } from './events/message-sent.event.js';
export { MessageDeliveredEvent } from './events/message-delivered.event.js';
export { MessageReadEvent } from './events/message-read.event.js';
export { MessageFailedEvent } from './events/message-failed.event.js';
export { MessageRetryingEvent } from './events/message-retrying.event.js';
export { MessageDeadLetteredEvent } from './events/message-dead-lettered.event.js';
export { MessageReceivedEvent } from './events/message-received.event.js';
export { type IMessageSender, MESSAGE_SENDER } from './ports/message-sender.port.js';
